# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # Trigger every hour
  schedule:
  - cron: "0 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Ruby for use with actions
      uses: actions/setup-ruby@v1
    - name: Generate report
      run: |
        sudo apt-get -y install curl
        bash run.sh
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.1.2
      with:
        commit_message: Update report
        # File pattern used for `git add`. For example `src/\*.js`
        file_pattern: report.json
